# Generated by Django 4.2.3 on 2023-12-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manager'),
        ),
    ]
